<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubcategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subcategories')
        ->insert([
            ['name' => 'Python', 'slug' => 'python', 'logo' => 'https://hackr.io/tutorials/python/logo-python.svg?ver=1562823957', 'category_id' => '1'],
            ['name' => 'JavaScript', 'slug' => 'javascript', 'logo' => 'https://hackr.io/tutorials/javascript/logo-javascript.svg?ver=1583168983', 'category_id' => '1'],
            ['name' => 'Android Development', 'slug' => 'android-development', 'logo' => 'https://hackr.io/tutorials/android-development/logo-android-development.svg?ver=1583169083', 'category_id' => '1'],
            ['name' => 'Java', 'slug' => 'java', 'logo' => 'https://hackr.io/tutorials/java/logo-java.svg?ver=1579862171', 'category_id' => '1'],
            ['name' => 'Data Structures and Algorithms', 'slug' => 'data-structures-and-algorithms', 'logo' => 'https://hackr.io/tutorials/data-structures-algorithms/logo-data-structures-algorithms.svg?ver=1550834269', 'category_id' => '1'],
            ['name' => 'C++', 'slug' => 'c-plus-plus', 'logo' => 'https://hackr.io/tutorials/c-plus-plus/logo-c-plus-plus.svg?ver=1579861999', 'category_id' => '1'],
            ['name' => 'React', 'slug' => 'react', 'logo' => 'https://hackr.io/tutorials/react/logo-react.svg?ver=1555134603', 'category_id' => '1'],
            ['name' => 'Angular', 'slug' => 'angular', 'logo' => 'https://hackr.io/tutorials/angular/logo-angular.svg?ver=1579862367', 'category_id' => '1'],
            ['name' => 'HTML 5', 'slug' => 'html-5', 'logo' => 'https://hackr.io/tutorials/html-5/logo-html-5.svg?ver=1555389548', 'category_id' => '1'],
            ['name' => 'CSS', 'slug' => 'css', 'logo' => 'https://hackr.io/tutorials/css/logo-css.svg?ver=1550727061', 'category_id' => '1'],
            ['name' => 'C', 'slug' => 'c', 'logo' => 'https://hackr.io/tutorials/c/logo-c.svg?ver=1553674176', 'category_id' => '1'],
            ['name' => 'PHP', 'slug' => 'php', 'logo' => 'https://hackr.io/tutorials/php/logo-php.svg?ver=1579862212', 'category_id' => '1'],
            ['name' => 'Git', 'slug' => 'git', 'logo' => 'https://hackr.io/tutorials/git/logo-git.svg?ver=1550796487', 'category_id' => '1'],
            ['name' => 'Bootstrap', 'slug' => 'bootstrap', 'logo' => 'https://hackr.io/tutorials/bootstrap/logo-bootstrap.svg?ver=1555328097', 'category_id' => '1'],
            ['name' => 'C#', 'slug' => 'c-sharp', 'logo' => 'https://hackr.io/tutorials/c-sharp/logo-c-sharp.svg?ver=1550834232', 'category_id' => '1'],
            ['name' => 'Information Security & Ethical Hacking', 'slug' => 'information-security-and-ethical-hacking', 'logo' => 'https://hackr.io/tutorials/information-security-ethical-hacking/logo-information-security-ethical-hacking.svg?ver=1579690729', 'category_id' => '1'],
            ['name' => 'Blockhain Programming', 'slug' => 'blockchain-programming', 'logo' => 'https://hackr.io/tutorials/blockchain-programming/logo-blockchain-programming.svg?ver=1550824665', 'category_id' => '1'],
            ['name' => 'MySQL', 'slug' => 'mysql', 'logo' => 'https://hackr.io/tutorials/mysql/logo-mysql.svg?ver=1550613740', 'category_id' => '1'],
            ['name' => 'Django', 'slug' => 'django', 'logo' => 'https://hackr.io/tutorials/django/logo-django.svg?ver=1579862450', 'category_id' => '1'],
            ['name' => 'SQL', 'slug' => 'sql', 'logo' => 'https://hackr.io/tutorials/sql/logo-sql.svg?ver=1555309685', 'category_id' => '1'],
            ['name' => 'Arduino', 'slug' => 'arduino', 'logo' => 'https://hackr.io/tutorials/arduino/logo-arduino.svg?ver=1551766080', 'category_id' => '1'],
            ['name' => 'Unity', 'slug' => 'unity', 'logo' => 'https://hackr.io/tutorials/unity/logo-unity.svg?ver=1579691365', 'category_id' => '1'],
            ['name' => 'React Native', 'slug' => 'react-native', 'logo' => 'https://hackr.io/tutorials/react-native/logo-react-native.svg?ver=1555132575', 'category_id' => '1'],
            ['name' => 'jQuery', 'slug' => 'jquery', 'logo' => 'https://hackr.io/tutorials/jquery/logo-jquery.svg?ver=1557130183', 'category_id' => '1'],
            ['name' => 'Intro to Programming', 'slug' => 'intro-to-programming', 'logo' => 'https://hackr.io/tutorials/intro-to-programming/logo-intro-to-programming.svg?ver=1550761991', 'category_id' => '1'],
            ['name' => 'Vue.js', 'slug' => 'vue-js', 'logo' => 'https://hackr.io/tutorials/vue-js/logo-vue-js.svg?ver=1555390471', 'category_id' => '1'],
            ['name' => 'Bitcoin', 'slug' => 'bitcoin', 'logo' => 'https://hackr.io/tutorials/bitcoin/logo-bitcoin.svg?ver=1552469443', 'category_id' => '1'],
            ['name' => 'Go', 'slug' => 'go', 'logo' => 'https://hackr.io/tutorials/golang/logo-golang.svg?ver=1555401655', 'category_id' => '1'],
            ['name' => 'Flutter', 'slug' => 'flutter', 'logo' => 'https://hackr.io/tutorials/flutter/logo-flutter.svg?ver=1579862938', 'category_id' => '1'],
            ['name' => 'ASP.NET', 'slug' => 'asp-net', 'logo' => 'https://hackr.io/tutorials/asp-net/logo-asp-net.svg?ver=1555328015', 'category_id' => '1'],
            ['name' => 'iOS Swift', 'slug' => 'ios-swift', 'logo' => 'https://hackr.io/tutorials/ios-swift/logo-ios-swift.svg?ver=1550689130', 'category_id' => '1'],
            ['name' => 'Kotlin', 'slug' => 'kotlin', 'logo' => 'https://hackr.io/tutorials/kotlin/logo-kotlin.svg?ver=1555389603', 'category_id' => '1'],
            ['name' => 'TypeScript', 'slug' => 'typescript', 'logo' => 'https://hackr.io/tutorials/typescript/logo-typescript.svg?ver=1550646462', 'category_id' => '1'],
            ['name' => 'Java Spring Framework', 'slug' => 'java-spring-framework', 'logo' => 'https://hackr.io/tutorials/java-spring-framework/logo-java-spring-framework.svg?ver=1555390385', 'category_id' => '1'],
            ['name' => 'Laravel', 'slug' => 'laravel', 'logo' => 'https://hackr.io/tutorials/laravel/logo-laravel.svg?ver=1550762399', 'category_id' => '1'],
            ['name' => 'Ruby', 'slug' => 'ruby', 'logo' => 'https://hackr.io/tutorials/ruby/logo-ruby.svg?ver=1550555255', 'category_id' => '1'],
            ['name' => 'Google Analytics', 'slug' => 'google-analytics', 'logo' => 'https://hackr.io/tutorials/google-analytics/logo-google-analytics.svg?ver=1551354757', 'category_id' => '1'],
            ['name' => 'Redux', 'slug' => 'redux', 'logo' => 'https://hackr.io/tutorials/redux/logo-redux.svg?ver=1551354757', 'category_id' => '1'],
            ['name' => 'SEO', 'slug' => 'seo', 'logo' => 'https://hackr.io/tutorials/seo/logo-seo.svg?ver=1550050459', 'category_id' => '1'],
            ['name' => 'PostgreSQL', 'slug' => 'postgresql', 'logo' => 'https://hackr.io/tutorials/postgresql/logo-postgresql.svg?ver=1555390079', 'category_id' => '1'],
            ['name' => 'Growth Hacking', 'slug' => 'growth-hacking', 'logo' => 'https://hackr.io/tutorials/growth-hacking/logo-growth-hacking.svg?ver=1551354757', 'category_id' => '1'],
            ['name' => 'Electron', 'slug' => 'electron', 'logo' => 'https://hackr.io/tutorials/electron/logo-electron.svg?ver=1551354757', 'category_id' => '1'],
            ['name' => 'Software Testing', 'slug' => 'software-testing', 'logo' => 'https://hackr.io/tutorials/software-testing/logo-software-testing.svg?ver=1553834045', 'category_id' => '1'],
            ['name' => 'Website Performance', 'slug' => 'website-performance', 'logo' => 'https://hackr.io/tutorials/website-performance/logo-website-performance.svg?ver=1551354757', 'category_id' => '1'],
            ['name' => 'Visual Basic .NET', 'slug' => 'visual-basic-net', 'logo' => 'https://hackr.io/tutorials/visual-basic-net-vb/logo-visual-basic-net-vb.svg?ver=1551354757', 'category_id' => '1'],
            ['name' => 'Elastic Search', 'slug' => 'elastic-search', 'logo' => 'https://hackr.io/tutorials/elastic-search/logo-elastic-search.svg?ver=1558117410', 'category_id' => '1'],
            ['name' => 'Ruby on Rails', 'slug' => 'ruby-on-rails', 'logo' => 'https://hackr.io/tutorials/ruby-on-rails/logo-ruby-on-rails.svg?ver=1551354757', 'category_id' => '1'],
            ['name' => 'Ionic', 'slug' => 'ionic', 'logo' => 'https://hackr.io/tutorials/ionic/logo-ionic.svg?ver=1555132763', 'category_id' => '1'],
            ['name' => 'Scala', 'slug' => 'scala', 'logo' => 'https://hackr.io/tutorials/scala/logo-scala.svg?ver=1556099539', 'category_id' => '1'],
            ['name' => 'Virtual Reality', 'slug' => 'virtual-reality', 'logo' => 'https://hackr.io/tutorials/virtual-reality/logo-virtual-reality.svg?ver=1563364635', 'category_id' => '1'],
            ['name' => 'Unreal Engine', 'slug' => 'unreal-engine', 'logo' => 'https://hackr.io/tutorials/unreal-engine/logo-unreal-engine.svg?ver=1551354757', 'category_id' => '1'],
            ['name' => 'Selenium', 'slug' => 'selenium', 'logo' => 'https://hackr.io/tutorials/selenium/logo-selenium.svg?ver=1556099522', 'category_id' => '1'],
            ['name' => 'Alexa Skills Kit', 'slug' => 'alexa-skills-kit', 'logo' => 'https://hackr.io/tutorials/alexa-skills-kit-ask/logo-alexa-skills-kit-ask.svg?ver=1554107807', 'category_id' => '1'],
            ['name' => 'Elixir', 'slug' => 'elixir', 'logo' => 'https://hackr.io/tutorials/elixir/logo-elixir.svg?ver=1579691321', 'category_id' => '1'],
            ['name' => 'Solidity', 'slug' => 'solidity', 'logo' => 'https://hackr.io/tutorials/solidity/logo-solidity.svg?ver=1553831680', 'category_id' => '1'],
            ['name' => 'Xamarin', 'slug' => 'xamarin', 'logo' => 'https://hackr.io/tutorials/xamarin/logo-xamarin.svg?ver=1555132966', 'category_id' => '1'],
            ['name' => 'Artifical Intelligence', 'slug' => 'artificial-intelligence', 'logo' => 'https://hackr.io/tutorials/artificial-intelligence-ai/logo-artificial-intelligence-ai.svg?ver=1555234239', 'category_id' => '2'],
            ['name' => 'Machine Learning', 'slug' => 'machine-learning', 'logo' => 'https://hackr.io/tutorials/machine-learning-ml/logo-machine-learning-ml.svg?ver=1559644608', 'category_id' => '2'],
            ['name' => 'Data Science', 'slug' => 'data-science', 'logo' => 'https://hackr.io/tutorials/data-science/logo-data-science.svg?ver=1555775500', 'category_id' => '2'],
            ['name' => 'Deep Learning', 'slug' => 'deep-learning', 'logo' => 'https://hackr.io/tutorials/deep-learning/logo-deep-learning.svg?ver=1576625961', 'category_id' => '2'],
            ['name' => 'R', 'slug' => 'r', 'logo' => 'https://hackr.io/tutorials/r/logo-r.svg?ver=1563444139', 'category_id' => '2'],
            ['name' => 'TensorFlow', 'slug' => 'tensorflow', 'logo' => 'https://hackr.io/tutorials/tensorflow/logo-tensorflow.svg?ver=1563364741', 'category_id' => '2'],
            ['name' => 'Hadoop', 'slug' => 'hadoop', 'logo' => 'https://hackr.io/tutorials/hadoop-big-data/logo-hadoop-big-data.svg?ver=1555234281', 'category_id' => '2'],
            ['name' => 'Apache Spark', 'slug' => 'apache-spark', 'logo' => 'https://hackr.io/tutorials/apache-spark/logo-apache-spark.svg?ver=1555327926', 'category_id' => '2'],
            ['name' => 'Linux System Administration', 'slug' => 'linux-system-administration', 'logo' => 'https://hackr.io/tutorials/linux-system-administration/logo-linux-system-administration.svg?ver=1555389741', 'category_id' => '3'],
            ['name' => 'AWS', 'slug' => 'aws', 'logo' => 'https://hackr.io/tutorials/amazon-web-services-aws/logo-amazon-web-services-aws.svg?ver=1555328044', 'category_id' => '3'],
            ['name' => 'Docker', 'slug' => 'docker', 'logo' => 'https://hackr.io/tutorials/docker/logo-docker.svg?ver=1555389348', 'category_id' => '3'],
            ['name' => 'Google Cloud Platform', 'slug' => 'google-cloud-platform', 'logo' => 'https://hackr.io/tutorials/google-cloud-platform/logo-google-cloud-platform.svg?ver=1551354757', 'category_id' => '3'],
            ['name' => 'Kubernetes', 'slug' => 'kubernetes', 'logo' => 'https://hackr.io/tutorials/kubernetes/logo-kubernetes.svg?ver=1555389652', 'category_id' => '3'],
            ['name' => 'Jenkins', 'slug' => 'jenkins', 'logo' => 'https://hackr.io/tutorials/jenkins/logo-jenkins.svg?ver=1560403209', 'category_id' => '3'],
            ['name' => 'Ansible', 'slug' => 'ansible', 'logo' => 'https://hackr.io/tutorials/ansible/logo-ansible.svg?ver=1579862041', 'category_id' => '3'],
            ['name' => 'System Architecture', 'slug' => 'system-architecture', 'logo' => 'https://hackr.io/tutorials/system-architecture/logo-system-architecture.svg?ver=1551354757', 'category_id' => '3'],
            ['name' => 'Microsoft Azure', 'slug' => 'mirosoft-azure', 'logo' => 'https://hackr.io/tutorials/microsoft-azure/logo-microsoft-azure.svg?ver=1551354757', 'category_id' => '3'],
            ['name' => 'Windows Server Administration', 'slug' => 'windows-server-administration', 'logo' => 'https://hackr.io/tutorials/windows-server-administration/logo-windows-server-administration.svg?ver=1551354757', 'category_id' => '3'],
            ['name' => 'Apache Kafka', 'slug' => 'apache-kafka', 'logo' => 'https://hackr.io/tutorials/apache-kafka/logo-apache-kafka.svg?ver=1551354757', 'category_id' => '3'],
            ['name' => 'Serverless Computing', 'slug' => 'serverless-computing', 'logo' => 'https://hackr.io/tutorials/serverless-computing/logo-serverless-computing.svg?ver=1551354757', 'category_id' => '3'],
            ['name' => 'Vagrant', 'slug' => 'vagrant', 'logo' => 'https://hackr.io/tutorials/vagrant/logo-vagrant.svg?ver=1557980642', 'category_id' => '3'],
            ['name' => 'Puppet', 'slug' => 'puppet', 'logo' => 'https://hackr.io/tutorials/puppet/logo-puppet.svg?ver=1558177620', 'category_id' => '3'],
            ['name' => 'Photoshop', 'slug' => 'photoshop', 'logo' => 'https://hackr.io/tutorials/photoshop/logo-photoshop.svg?ver=1550076795', 'category_id' => '4'],
            ['name' => 'User Interface Design', 'slug' => 'user-interface-design', 'logo' => 'https://hackr.io/tutorials/user-interface-design/logo-user-interface-design.svg?ver=1559981005', 'category_id' => '4'],
            ['name' => 'Game Design', 'slug' => 'game-design', 'logo' => 'https://hackr.io/tutorials/game-design/logo-game-design.svg?ver=1550671635', 'category_id' => '4'],
            ['name' => 'Design Thinking', 'slug' => 'design-thinking', 'logo' => 'https://hackr.io/tutorials/design-thinking/logo-design-thinking.svg?ver=1550483195', 'category_id' => '4'],
            ['name' => 'Illustrator', 'slug' => 'illustrator', 'logo' => 'https://hackr.io/tutorials/adobe-illustrator/logo-adobe-illustrator.svg?ver=1550076656', 'category_id' => '4'],
            ['name' => 'Adobe After Effects', 'slug' => 'adobe-after-effects', 'logo' => 'https://hackr.io/tutorials/adobe-after-effects/logo-adobe-after-effects.svg?ver=1550033265', 'category_id' => '4'],
            ['name' => 'Adobe Experience Design', 'slug' => 'adobe-experience-design', 'logo' => 'https://hackr.io/tutorials/adobe-experience-design/logo-adobe-experience-design.svg?ver=1549985484', 'category_id' => '4'],
            ['name' => 'Sketch', 'slug' => 'sketch', 'logo' => 'https://hackr.io/tutorials/sketch/logo-sketch.svg?ver=1550326944', 'category_id' => '4'],
            ['name' => 'Adobe Premier Pro', 'slug' => 'adobe-premier-pro', 'logo' => 'https://hackr.io/tutorials/adobe-premier-pro/logo-adobe-premier-pro.svg?ver=1549393149', 'category_id' => '4'],
            ['name' => 'Adobe Lightroom', 'slug' => 'adobe-lightroom', 'logo' => 'https://hackr.io/tutorials/adobe-lightroom/logo-adobe-lightroom.svg?ver=1550669322', 'category_id' => '4'],
            ['name' => 'User Experience Design', 'slug' => 'user-experience-design', 'logo' => 'https://hackr.io/tutorials/user-experience-design/logo-user-experience-design.svg?ver=1559978845', 'category_id' => '4'],
            ['name' => 'Blender', 'slug' => 'blender', 'logo' => 'https://hackr.io/tutorials/blender/logo-blender.svg?ver=1550467298', 'category_id' => '4'],
            ['name' => 'Affinity Photo', 'slug' => 'affinity-photo', 'logo' => 'https://hackr.io/tutorials/affinity-photo/logo-affinity-photo.svg?ver=1550669392', 'category_id' => '4'],
            ['name' => 'Color Theory', 'slug' => 'color-theory', 'logo' => 'https://hackr.io/tutorials/color-theory/logo-color-theory.svg?ver=1549985558', 'category_id' => '4'],
            ['name' => 'Adobe Indesign', 'slug' => 'adobe-indesign', 'logo' => 'https://hackr.io/tutorials/adobe-indesign/logo-adobe-indesign.svg?ver=1549098430', 'category_id' => '4'],
            ['name' => 'Information Architecture', 'slug' => 'information-architecture', 'logo' => 'https://hackr.io/tutorials/information-architecture/logo-information-architecture.svg?ver=1550384494', 'category_id' => '4'],
            ['name' => 'Daz Studio', 'slug' => 'daz-studio', 'logo' => 'https://hackr.io/tutorials/daz-studio/logo-daz-studio.svg?ver=1548759784', 'category_id' => '4'],
            ['name' => 'Interaction Design', 'slug' => 'interaction-design', 'logo' => 'https://hackr.io/tutorials/interaction-design/logo-interaction-design.svg?ver=1559978270', 'category_id' => '4'],
            ['name' => 'Prototyping', 'slug' => 'prototyping', 'logo' => 'https://hackr.io/tutorials/prototyping/logo-prototyping.svg?ver=1550384346', 'category_id' => '4'],
            ['name' => 'Branding', 'slug' => 'branding', 'logo' => 'https://hackr.io/tutorials/branding/logo-branding.svg?ver=1548759784', 'category_id' => '4'],
            ['name' => 'Drawing', 'slug' => 'drawing', 'logo' => 'https://hackr.io/tutorials/drawing/logo-drawing.svg?ver=1550076652', 'category_id' => '4'],
            ['name' => 'Content Strategy', 'slug' => 'content-strategy', 'logo' => 'https://hackr.io/tutorials/content-strategy/logo-content-strategy.svg?ver=1548759783', 'category_id' => '4'],
            ['name' => 'Product Design', 'slug' => 'product-design', 'logo' => 'https://hackr.io/tutorials/product-design/logo-product-design.svg?ver=1548759784', 'category_id' => '4'],
            ['name' => 'Autodesk Maya', 'slug' => 'autodesk-maya', 'logo' => 'https://hackr.io/tutorials/autodesk-maya/logo-autodesk-maya.svg?ver=1554094371', 'category_id' => '4'],
            ['name' => 'Digital Painting', 'slug' => 'digital-painting', 'logo' => 'https://hackr.io/tutorials/digital-painting/logo-digital-painting.svg?ver=1550076640', 'category_id' => '4'],
            ['name' => 'Autodesk 3ds Max', 'slug' => 'autodesk-3ds-max', 'logo' => 'https://hackr.io/tutorials/autodesk-3ds-max/logo-autodesk-3ds-max.svg?ver=1548759784', 'category_id' => '4'],
            ['name' => 'Industrial Design', 'slug' => 'industrial-design', 'logo' => 'https://hackr.io/tutorials/industrial-design/logo-industrial-design.svg?ver=1548759784', 'category_id' => '4'],
            ['name' => 'Cinema 4D', 'slug' => 'cinema-4d', 'logo' => 'https://hackr.io/tutorials/cinema-4d/logo-cinema-4d.svg?ver=1549761800', 'category_id' => '4'],
            ['name' => 'UX Research', 'slug' => 'ux-research', 'logo' => 'https://hackr.io/tutorials/ux-research/logo-ux-research.svg?ver=1548822061', 'category_id' => '4'],
            ['name' => 'Wireframing', 'slug' => 'wireframing', 'logo' => 'https://hackr.io/tutorials/wireframing/logo-wireframing.svg?ver=1549985604', 'category_id' => '4'],
            ['name' => 'Typography', 'slug' => 'Typography', 'logo' => 'https://hackr.io/tutorials/typography/logo-typography.svg?ver=1549985595', 'category_id' => '4'],
            ['name' => 'Affinity Designer', 'slug' => 'affinity-designer', 'logo' => 'https://hackr.io/tutorials/affinity-designer/logo-affinity-designer.svg?ver=1549985573', 'category_id' => '4'],
            ['name' => 'Figma', 'slug' => 'figma', 'logo' => 'https://hackr.io/tutorials/figma/logo-figma.svg?ver=1550735263', 'category_id' => '4'],
            ['name' => 'Inkscape', 'slug' => 'inkscape', 'logo' => 'https://hackr.io/tutorials/inkscape/logo-inkscape.svg?ver=1551354757', 'category_id' => '4'],
            ['name' => 'Sketchbook Pro', 'slug' => 'sketchbook-pro', 'logo' => 'https://hackr.io/tutorials/sketchbook-pro/logo-sketchbook-pro.svg?ver=1548759784', 'category_id' => '4'],
            ['name' => 'InVision', 'slug' => 'invision', 'logo' => 'https://hackr.io/tutorials/invision/logo-invision.svg?ver=1548759783', 'category_id' => '4'],
            ['name' => 'UX Pin', 'slug' => 'ux-pin', 'logo' => 'https://hackr.io/tutorials/ux-pin/logo-ux-pin.svg?ver=1556099549', 'category_id' => '4'],
            ['name' => 'Principle', 'slug' => 'principle', 'logo' => 'https://hackr.io/tutorials/principle/logo-principle.svg?ver=1549769352', 'category_id' => '4'],
            ['name' => 'Origami Studio', 'slug' => 'origami-studio', 'logo' => 'https://hackr.io/tutorials/origami-studio/logo-origami-studio.svg?ver=1548759783', 'category_id' => '4'],
            ['name' => 'Framer', 'slug' => 'framer', 'logo' => 'https://hackr.io/tutorials/framer/logo-framer.svg?ver=1548759782', 'category_id' => '4'],
            ['name' => 'Marvel', 'slug' => 'marvel', 'logo' => 'https://hackr.io/tutorials/marvel/logo-marvel.svg?ver=1550562876', 'category_id' => '4'],
        ]);
    }
}
